-- Seed: initial campaign rules for Week 3 VIP clusters
-- Steel/Metals Kalamboli · Corrugated/Packaging Bhiwandi · Industrial Adhesives Navi Mumbai
-- Rules were seeded via POST /api/admin/marketing/rules on 2026-06-15.
-- This file is intentionally empty to prevent duplicate inserts on future deployments.
